apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: chat-backend
  ports:
    - protocol: TCP
      port: 80         # External access
      targetPort: 80   # Inside container
  type: LoadBalancer  # Expose backend outside Kubernetes
