apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: chat-server
          image: myrepo/chat-server:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/chatdb"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
spec:
  selector:
    app: chat-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
